services:
  db:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tanks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

  web:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
      - ./html:/var/www/html
    depends_on:
      - php
      - db
    networks:
      - my_network

  php:
    build: .
    container_name: php
    volumes:
      - ./html:/var/www/html  # Монтируем директорию с файлами
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
