services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tanks
    ports:
     - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network



#  flask:
#    build:
#      context: ./flask_api
#    container_name: flask_app
#    command: gunicorn --bind 0.0.0.0:5000 "app:create_app()"
#    expose:
#      - "5000"
#    environment:
#      - FLASK_ENV=production
#    volumes:
#      - ./flask_api:/var/www/html/flask_app
#    networks:
#      - app_network

  php:
    build: ./php
    volumes:
      - ./php:/var/www/html/api
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html/static
    depends_on:
      - php
#      - flask
      - db
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
