services:
  db:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tanks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

  flask:
    build:
      context: ./html/Tanks
    container_name: flask_app
    command: gunicorn --bind 0.0.0.0:5000 "app:create_app()"
    expose:
      - "5000"
    environment:
     - FLASK_ENV=production
    volumes:
      - ./html/Tanks:/flask_app  # Для разработки - монтируем код
    networks:
      - my_network

  php:
    build:
      context: .
    container_name: php
    volumes:
      - ./html:/var/www/html
    networks:
      - my_network

  web:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
    depends_on:
      - php
      - flask
      - db
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge