services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tanks
    ports:
     - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgresql
    networks:
      - app_network

  php:
    build: ./php
    volumes:
      - ./php:/var/www/html/api
      - ./html:/var/www/html/static
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    container_name: php-fpm
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html/static
    depends_on:
      - php
      - db
    container_name: nginx_server
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
